"""Extract per-page PDF text into search-docs.js for client-side full-text search.

Reuses the textbook registry and Subject-Section parsing from generate_manifest.py.
Rerun whenever the PDFs change (after adding a textbook, or after strip_annotations.py):

    python build_search_index.py
"""

import json
import os
import re

import fitz  # PyMuPDF

from generate_manifest import TEXTBOOKS, build_textbook

ROOT = os.path.dirname(os.path.abspath(__file__))
MIN_CHARS = 20
_WS = re.compile(r"\s+")


def main():
    docs = []
    next_id = 0

    for cfg in TEXTBOOKS:
        tb = build_textbook(cfg)
        for chapter in tb["chapters"]:
            for sec in chapter["sections"]:
                path = os.path.join(ROOT, sec["file"])
                doc = fitz.open(path)
                for i, page in enumerate(doc):
                    text = _WS.sub(" ", page.get_text("text")).strip()
                    if len(text) < MIN_CHARS:
                        continue
                    docs.append({
                        "id": next_id,
                        "subject": chapter["subject"],
                        "section": sec["name"],
                        "file": sec["file"],
                        "page": i + 1,  # 1-based, matches PDF #page=
                        "text": text,
                    })
                    next_id += 1
                doc.close()

    payload = json.dumps(docs, ensure_ascii=False)
    out = os.path.join(ROOT, "search-docs.js")
    with open(out, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by build_search_index.py - do not edit by hand.\n")
        f.write("window.SEARCH_DOCS = " + payload + ";\n")

    size_mb = os.path.getsize(out) / 1048576
    print(f"Wrote search-docs.js: {len(docs)} page docs, {size_mb:.2f} MB")


if __name__ == "__main__":
    main()
