"""Scan textbook PDF folders and emit manifest.js for the landing page.

Add a new textbook by dropping its folder of PDFs in the repo and appending an
entry to TEXTBOOKS below, then rerun:  python generate_manifest.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent

# --- Textbook registry -------------------------------------------------------
# pdf_dir is relative to this repo root. Filenames are parsed as
# "Subject-Section.pdf" (split on the first hyphen); files without a hyphen are
# grouped under the RAPID_REVIEW subject.
TEXTBOOKS = [
    {
        "id": "first-aid",
        "title": "First Aid for the USMLE Step 1",
        "edition": "2025 · 35th ed.",
        "icon": "\U0001F4D5",  # closed book
        "pdf_dir": "First Aid/PDFs",
    },
]

RAPID_REVIEW = "Rapid Review"

# Preferred subject order, mirroring First Aid's General Principles -> Organ
# Systems structure. Subjects not listed are appended alphabetically; the
# Rapid Review appendix files always go last.
SUBJECT_ORDER = [
    # General Principles
    "Biochemistry",
    "Immunology",
    "Microbiology",
    "Pathology",
    "Pharmacology",
    "Public Health Sciences",
    # Organ Systems
    "Cardiovascular",
    "Endocrine",
    "Gastrointestinal",
    "Hematology And Oncology",
    "Musculoskeletal, Skin, And Connective Tissue",
    "Neurology",
    "Psychiatry",
    "Renal",
    "Reproductive",
    "Respiratory",
    # Appendix
    RAPID_REVIEW,
]


def subject_sort_key(subject):
    """Known subjects keep their curated order; unknown ones sort after,
    alphabetically. Rapid Review always lands last."""
    if subject in SUBJECT_ORDER:
        return (0, SUBJECT_ORDER.index(subject), "")
    return (1, 0, subject.lower())


def build_textbook(cfg):
    pdf_dir = ROOT / cfg["pdf_dir"]
    if not pdf_dir.is_dir():
        raise SystemExit(f"PDF folder not found: {pdf_dir}")

    subjects = {}  # subject -> list of {name, file}
    for pdf in pdf_dir.glob("*.pdf"):
        stem = pdf.stem
        if "-" in stem:
            subject, section = stem.split("-", 1)
            subject, section = subject.strip(), section.strip()
        else:
            subject, section = RAPID_REVIEW, stem.strip()
        # repo-relative POSIX path for use as a URL
        rel = pdf.relative_to(ROOT).as_posix()
        subjects.setdefault(subject, []).append({"name": section, "file": rel})

    chapters = []
    for subject in sorted(subjects, key=subject_sort_key):
        sections = sorted(subjects[subject], key=lambda s: s["name"].lower())
        chapters.append({"subject": subject, "sections": sections})

    total = sum(len(c["sections"]) for c in chapters)
    return {
        "id": cfg["id"],
        "title": cfg["title"],
        "edition": cfg["edition"],
        "icon": cfg["icon"],
        "chapters": chapters,
        "sectionCount": total,
    }


def main():
    textbooks = [build_textbook(cfg) for cfg in TEXTBOOKS]

    manifest = {"textbooks": textbooks}
    payload = json.dumps(manifest, indent=2, ensure_ascii=False)
    out = ROOT / "manifest.js"
    out.write_text(
        "// Auto-generated by generate_manifest.py - do not edit by hand.\n"
        f"window.MANIFEST = {payload};\n",
        encoding="utf-8",
    )

    for tb in textbooks:
        print(f"{tb['title']}: {len(tb['chapters'])} subjects, "
              f"{tb['sectionCount']} sections")
    print(f"Wrote {out.relative_to(ROOT).as_posix()}")


if __name__ == "__main__":
    main()
