// Auto-generated by generate_manifest.py - do not edit by hand.
window.MANIFEST = {
  "textbooks": [
    {
      "id": "first-aid",
      "title": "First Aid for the USMLE Step 1",
      "edition": "2025 · 35th ed.",
      "icon": "📕",
      "chapters": [
        {
          "subject": "Biochemistry",
          "sections": [
            {
              "name": "Genetics",
              "file": "First Aid/PDFs/Biochemistry-Genetics.pdf"
            },
            {
              "name": "Laboratory Techniques",
              "file": "First Aid/PDFs/Biochemistry-Laboratory Techniques.pdf"
            },
            {
              "name": "Metabolism",
              "file": "First Aid/PDFs/Biochemistry-Metabolism.pdf"
            },
            {
              "name": "Molecular",
              "file": "First Aid/PDFs/Biochemistry-Molecular.pdf"
            },
            {
              "name": "Nutrition",
              "file": "First Aid/PDFs/Biochemistry-Nutrition.pdf"
            }
          ]
        },
        {
          "subject": "Immunology",
          "sections": [
            {
              "name": "Cellular Components",
              "file": "First Aid/PDFs/Immunology-Cellular Components.pdf"
            },
            {
              "name": "Immune Responses",
              "file": "First Aid/PDFs/Immunology-Immune Responses.pdf"
            },
            {
              "name": "Immunosuppressants",
              "file": "First Aid/PDFs/Immunology-Immunosuppressants.pdf"
            },
            {
              "name": "Lymphoid Structures",
              "file": "First Aid/PDFs/Immunology-Lymphoid Structures.pdf"
            }
          ]
        },
        {
          "subject": "Microbiology",
          "sections": [
            {
              "name": "Antimicrobials",
              "file": "First Aid/PDFs/Microbiology-Antimicrobials.pdf"
            },
            {
              "name": "Basic Bacteriology",
              "file": "First Aid/PDFs/Microbiology-Basic Bacteriology.pdf"
            },
            {
              "name": "Clinical Bacteriology",
              "file": "First Aid/PDFs/Microbiology-Clinical Bacteriology.pdf"
            },
            {
              "name": "Mycology",
              "file": "First Aid/PDFs/Microbiology-Mycology.pdf"
            },
            {
              "name": "Parasitology",
              "file": "First Aid/PDFs/Microbiology-Parasitology.pdf"
            },
            {
              "name": "Systems",
              "file": "First Aid/PDFs/Microbiology-Systems.pdf"
            },
            {
              "name": "Virology",
              "file": "First Aid/PDFs/Microbiology-Virology.pdf"
            }
          ]
        },
        {
          "subject": "Pathology",
          "sections": [
            {
              "name": "Aging",
              "file": "First Aid/PDFs/Pathology-Aging.pdf"
            },
            {
              "name": "Cellular Injury",
              "file": "First Aid/PDFs/Pathology-Cellular Injury.pdf"
            },
            {
              "name": "Inflammation",
              "file": "First Aid/PDFs/Pathology-Inflammation.pdf"
            },
            {
              "name": "Neoplasia",
              "file": "First Aid/PDFs/Pathology-Neoplasia.pdf"
            }
          ]
        },
        {
          "subject": "Pharmacology",
          "sections": [
            {
              "name": "Autonomic Drugs",
              "file": "First Aid/PDFs/Pharmacology-Autonomic Drugs.pdf"
            },
            {
              "name": "Miscellaneous",
              "file": "First Aid/PDFs/Pharmacology-Miscellaneous.pdf"
            },
            {
              "name": "Pharmacokinetics And Pharmacodynamics",
              "file": "First Aid/PDFs/Pharmacology-Pharmacokinetics And Pharmacodynamics.pdf"
            },
            {
              "name": "Toxicities And Adverse Effects",
              "file": "First Aid/PDFs/Pharmacology-Toxicities And Adverse Effects.pdf"
            }
          ]
        },
        {
          "subject": "Public Health Sciences",
          "sections": [
            {
              "name": "Communication Skills",
              "file": "First Aid/PDFs/Public Health Sciences-Communication Skills.pdf"
            },
            {
              "name": "Epidemiology And Biostatistics",
              "file": "First Aid/PDFs/Public Health Sciences-Epidemiology And Biostatistics.pdf"
            },
            {
              "name": "Ethics",
              "file": "First Aid/PDFs/Public Health Sciences-Ethics.pdf"
            },
            {
              "name": "Healthcare Delivery",
              "file": "First Aid/PDFs/Public Health Sciences-Healthcare Delivery.pdf"
            }
          ]
        },
        {
          "subject": "Cardiovascular",
          "sections": [
            {
              "name": "Anatomy",
              "file": "First Aid/PDFs/Cardiovascular-Anatomy.pdf"
            },
            {
              "name": "Embryology",
              "file": "First Aid/PDFs/Cardiovascular-Embryology.pdf"
            },
            {
              "name": "Pathology",
              "file": "First Aid/PDFs/Cardiovascular-Pathology.pdf"
            },
            {
              "name": "Pharmacology",
              "file": "First Aid/PDFs/Cardiovascular-Pharmacology.pdf"
            },
            {
              "name": "Physiology",
              "file": "First Aid/PDFs/Cardiovascular-Physiology.pdf"
            }
          ]
        },
        {
          "subject": "Endocrine",
          "sections": [
            {
              "name": "Anatomy",
              "file": "First Aid/PDFs/Endocrine-Anatomy.pdf"
            },
            {
              "name": "Embryology",
              "file": "First Aid/PDFs/Endocrine-Embryology.pdf"
            },
            {
              "name": "Pathology",
              "file": "First Aid/PDFs/Endocrine-Pathology.pdf"
            },
            {
              "name": "Pharmacology",
              "file": "First Aid/PDFs/Endocrine-Pharmacology.pdf"
            },
            {
              "name": "Physiology",
              "file": "First Aid/PDFs/Endocrine-Physiology.pdf"
            }
          ]
        },
        {
          "subject": "Gastrointestinal",
          "sections": [
            {
              "name": "Embryology",
              "file": "First Aid/PDFs/Gastrointestinal-Embryology.pdf"
            },
            {
              "name": "Pathology",
              "file": "First Aid/PDFs/Gastrointestinal-Pathology.pdf"
            },
            {
              "name": "Pharmacology",
              "file": "First Aid/PDFs/Gastrointestinal-Pharmacology.pdf"
            },
            {
              "name": "Physiology",
              "file": "First Aid/PDFs/Gastrointestinal-Physiology.pdf"
            }
          ]
        },
        {
          "subject": "Hematology And Oncology",
          "sections": [
            {
              "name": "Anatomy",
              "file": "First Aid/PDFs/Hematology And Oncology-Anatomy.pdf"
            },
            {
              "name": "Embryology",
              "file": "First Aid/PDFs/Hematology And Oncology-Embryology.pdf"
            },
            {
              "name": "Pathology",
              "file": "First Aid/PDFs/Hematology And Oncology-Pathology.pdf"
            },
            {
              "name": "Pharmacology",
              "file": "First Aid/PDFs/Hematology And Oncology-Pharmacology.pdf"
            },
            {
              "name": "Physiology",
              "file": "First Aid/PDFs/Hematology And Oncology-Physiology.pdf"
            }
          ]
        },
        {
          "subject": "Musculoskeletal, Skin, And Connective Tissue",
          "sections": [
            {
              "name": "Anatomy And Physiology",
              "file": "First Aid/PDFs/Musculoskeletal, Skin, And Connective Tissue-Anatomy And Physiology.pdf"
            },
            {
              "name": "Dermatology",
              "file": "First Aid/PDFs/Musculoskeletal, Skin, And Connective Tissue-Dermatology.pdf"
            },
            {
              "name": "Pathology",
              "file": "First Aid/PDFs/Musculoskeletal, Skin, And Connective Tissue-Pathology.pdf"
            },
            {
              "name": "Pharmacology",
              "file": "First Aid/PDFs/Musculoskeletal, Skin, And Connective Tissue-Pharmacology.pdf"
            }
          ]
        },
        {
          "subject": "Neurology",
          "sections": [
            {
              "name": "Anatomy And Physiology",
              "file": "First Aid/PDFs/Neurology-Anatomy And Physiology.pdf"
            },
            {
              "name": "Embryology",
              "file": "First Aid/PDFs/Neurology-Embryology.pdf"
            },
            {
              "name": "Ophthalmology",
              "file": "First Aid/PDFs/Neurology-Ophthalmology.pdf"
            },
            {
              "name": "Otology",
              "file": "First Aid/PDFs/Neurology-Otology.pdf"
            },
            {
              "name": "Pathology",
              "file": "First Aid/PDFs/Neurology-Pathology.pdf"
            }
          ]
        },
        {
          "subject": "Psychiatry",
          "sections": [
            {
              "name": "Pathology",
              "file": "First Aid/PDFs/Psychiatry-Pathology.pdf"
            },
            {
              "name": "Pharmacology",
              "file": "First Aid/PDFs/Psychiatry-Pharmacology.pdf"
            },
            {
              "name": "Psychology",
              "file": "First Aid/PDFs/Psychiatry-Psychology.pdf"
            }
          ]
        },
        {
          "subject": "Renal",
          "sections": [
            {
              "name": "Anatomy",
              "file": "First Aid/PDFs/Renal-Anatomy.pdf"
            },
            {
              "name": "Embryology",
              "file": "First Aid/PDFs/Renal-Embryology.pdf"
            },
            {
              "name": "Pathology",
              "file": "First Aid/PDFs/Renal-Pathology.pdf"
            },
            {
              "name": "Pharmacology",
              "file": "First Aid/PDFs/Renal-Pharmacology.pdf"
            },
            {
              "name": "Physiology",
              "file": "First Aid/PDFs/Renal-Physiology.pdf"
            }
          ]
        },
        {
          "subject": "Reproductive",
          "sections": [
            {
              "name": "Anatomy",
              "file": "First Aid/PDFs/Reproductive-Anatomy.pdf"
            },
            {
              "name": "Embryology",
              "file": "First Aid/PDFs/Reproductive-Embryology.pdf"
            },
            {
              "name": "Pathology",
              "file": "First Aid/PDFs/Reproductive-Pathology.pdf"
            },
            {
              "name": "Pharmacology",
              "file": "First Aid/PDFs/Reproductive-Pharmacology.pdf"
            },
            {
              "name": "Physiology",
              "file": "First Aid/PDFs/Reproductive-Physiology.pdf"
            }
          ]
        },
        {
          "subject": "Respiratory",
          "sections": [
            {
              "name": "Anatomy",
              "file": "First Aid/PDFs/Respiratory-Anatomy.pdf"
            },
            {
              "name": "Embryology",
              "file": "First Aid/PDFs/Respiratory-Embryology.pdf"
            },
            {
              "name": "Pathology",
              "file": "First Aid/PDFs/Respiratory-Pathology.pdf"
            },
            {
              "name": "Pharmacology",
              "file": "First Aid/PDFs/Respiratory-Pharmacology.pdf"
            },
            {
              "name": "Physiology",
              "file": "First Aid/PDFs/Respiratory-Physiology.pdf"
            }
          ]
        },
        {
          "subject": "Rapid Review",
          "sections": [
            {
              "name": "Classic Labs And Findings",
              "file": "First Aid/PDFs/Classic Labs And Findings.pdf"
            },
            {
              "name": "Classic Presentations",
              "file": "First Aid/PDFs/Classic Presentations.pdf"
            },
            {
              "name": "Equation and Easily Confused Medications",
              "file": "First Aid/PDFs/Equation and Easily Confused Medications.pdf"
            },
            {
              "name": "Pathophysiology Of Important Diseases",
              "file": "First Aid/PDFs/Pathophysiology Of Important Diseases.pdf"
            }
          ]
        }
      ],
      "sectionCount": 78
    }
  ]
};
